// Code generated by protoc-gen-go-server. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v0.0.1
// source: admin/menu/menu.proto

package menu

import (
	context "context"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = grpc.Version

type MenuImpl struct {
	cc MenuClient
}

func NewMenuImpl(conn *grpc.ClientConn) *MenuImpl {
	return &MenuImpl{cc: NewMenuClient(conn)}
}

func (c *MenuImpl) GetMenu(ctx context.Context, in *GetMenuReq) (*GetMenuResp, error) {
	return c.cc.GetMenu(ctx, in)
}

func (c *MenuImpl) GetMenuList(ctx context.Context, in *GetMenuReq) (*GetMenuResp, error) {
	return c.cc.GetMenuList(ctx, in)
}
