// Code generated by protoc-gen-go-server. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v0.0.1
// source: admin/menu/menu.proto

package menu

import (
	context "context"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

type MenuImpl struct {
	cc MenuClient
}

func NewMenuImpl(client MenuClient) *MenuImpl {
	return &MenuImpl{client}
}

func (c *MenuImpl) GetMenu(ctx context.Context, in *GetMenuReq) (*GetMenuResp, error) {
	return c.cc.GetMenu(ctx, in)
}

func (c *MenuImpl) GetMenuList(ctx context.Context, in *GetMenuReq) (*GetMenuResp, error) {
	return c.cc.GetMenuList(ctx, in)
}
