// Code generated by protoc-gen-go-server. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v0.0.1
// source: admin/user/user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = grpc.Version

type UserImpl struct {
	cc UserClient
}

func NewUserImpl(conn *grpc.ClientConn) *UserImpl {
	return &UserImpl{cc: NewUserClient(conn)}
}

func (c *UserImpl) GetUserInfo(ctx context.Context, in *UserInfoReq) (*UserInfoResp, error) {
	return c.cc.GetUserInfo(ctx, in)
}
